<?php

/**
 * BaseAreaLevel2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $area1_id
 * @property string $description
 * @property AreaLevel1 $AreaLevel1
 * @property Doctrine_Collection $Person
 * @property Doctrine_Collection $AreaLevel3
 * 
 * @method integer             getArea1Id()     Returns the current record's "area1_id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method AreaLevel1          getAreaLevel1()  Returns the current record's "AreaLevel1" value
 * @method Doctrine_Collection getPerson()      Returns the current record's "Person" collection
 * @method Doctrine_Collection getAreaLevel3()  Returns the current record's "AreaLevel3" collection
 * @method AreaLevel2          setArea1Id()     Sets the current record's "area1_id" value
 * @method AreaLevel2          setDescription() Sets the current record's "description" value
 * @method AreaLevel2          setAreaLevel1()  Sets the current record's "AreaLevel1" value
 * @method AreaLevel2          setPerson()      Sets the current record's "Person" collection
 * @method AreaLevel2          setAreaLevel3()  Sets the current record's "AreaLevel3" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAreaLevel2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area_level2');
        $this->hasColumn('area1_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AreaLevel1', array(
             'local' => 'area1_id',
             'foreign' => 'id'));

        $this->hasMany('Person', array(
             'local' => 'id',
             'foreign' => 'address_area2'));

        $this->hasMany('AreaLevel3', array(
             'local' => 'id',
             'foreign' => 'area2_id'));
    }
}