<?php

/**
 * BaseDosyeAreaLevel2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $area1_id
 * @property string $description
 * @property DosyeAreaLevel1 $AreaLevel1
 * @property Doctrine_Collection $DosyePerson
 * @property Doctrine_Collection $DosyeAreaLevel3
 * 
 * @method integer             getArea1Id()         Returns the current record's "area1_id" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method DosyeAreaLevel1     getAreaLevel1()      Returns the current record's "AreaLevel1" value
 * @method Doctrine_Collection getDosyePerson()     Returns the current record's "DosyePerson" collection
 * @method Doctrine_Collection getDosyeAreaLevel3() Returns the current record's "DosyeAreaLevel3" collection
 * @method DosyeAreaLevel2     setArea1Id()         Sets the current record's "area1_id" value
 * @method DosyeAreaLevel2     setDescription()     Sets the current record's "description" value
 * @method DosyeAreaLevel2     setAreaLevel1()      Sets the current record's "AreaLevel1" value
 * @method DosyeAreaLevel2     setDosyePerson()     Sets the current record's "DosyePerson" collection
 * @method DosyeAreaLevel2     setDosyeAreaLevel3() Sets the current record's "DosyeAreaLevel3" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyeAreaLevel2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_area_level2');
        $this->hasColumn('area1_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DosyeAreaLevel1 as AreaLevel1', array(
             'local' => 'area1_id',
             'foreign' => 'id'));

        $this->hasMany('DosyePerson', array(
             'local' => 'id',
             'foreign' => 'address_area2'));

        $this->hasMany('DosyeAreaLevel3', array(
             'local' => 'id',
             'foreign' => 'area2_id'));
    }
}