<?php

/**
 * BaseDosyeGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $group_name
 * @property integer $photo_image_id
 * @property integer $avatar_image_id
 * @property string $description
 * @property date $due_date
 * @property Doctrine_Collection $SubGroups
 * @property Doctrine_Collection $Persons
 * @property Doctrine_Collection $Files
 * @property DosyeImage $AvatarImage
 * @property DosyeImage $PhotoImage
 * @property Doctrine_Collection $DosyeSubGroup
 * @property Doctrine_Collection $DosyeGroupPerson
 * @property Doctrine_Collection $DosyeGroupFile
 * 
 * @method string              getGroupName()        Returns the current record's "group_name" value
 * @method integer             getPhotoImageId()     Returns the current record's "photo_image_id" value
 * @method integer             getAvatarImageId()    Returns the current record's "avatar_image_id" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method date                getDueDate()          Returns the current record's "due_date" value
 * @method Doctrine_Collection getSubGroups()        Returns the current record's "SubGroups" collection
 * @method Doctrine_Collection getPersons()          Returns the current record's "Persons" collection
 * @method Doctrine_Collection getFiles()            Returns the current record's "Files" collection
 * @method DosyeImage          getAvatarImage()      Returns the current record's "AvatarImage" value
 * @method DosyeImage          getPhotoImage()       Returns the current record's "PhotoImage" value
 * @method Doctrine_Collection getDosyeSubGroup()    Returns the current record's "DosyeSubGroup" collection
 * @method Doctrine_Collection getDosyeGroupPerson() Returns the current record's "DosyeGroupPerson" collection
 * @method Doctrine_Collection getDosyeGroupFile()   Returns the current record's "DosyeGroupFile" collection
 * @method DosyeGroup          setGroupName()        Sets the current record's "group_name" value
 * @method DosyeGroup          setPhotoImageId()     Sets the current record's "photo_image_id" value
 * @method DosyeGroup          setAvatarImageId()    Sets the current record's "avatar_image_id" value
 * @method DosyeGroup          setDescription()      Sets the current record's "description" value
 * @method DosyeGroup          setDueDate()          Sets the current record's "due_date" value
 * @method DosyeGroup          setSubGroups()        Sets the current record's "SubGroups" collection
 * @method DosyeGroup          setPersons()          Sets the current record's "Persons" collection
 * @method DosyeGroup          setFiles()            Sets the current record's "Files" collection
 * @method DosyeGroup          setAvatarImage()      Sets the current record's "AvatarImage" value
 * @method DosyeGroup          setPhotoImage()       Sets the current record's "PhotoImage" value
 * @method DosyeGroup          setDosyeSubGroup()    Sets the current record's "DosyeSubGroup" collection
 * @method DosyeGroup          setDosyeGroupPerson() Sets the current record's "DosyeGroupPerson" collection
 * @method DosyeGroup          setDosyeGroupFile()   Sets the current record's "DosyeGroupFile" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyeGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_group');
        $this->hasColumn('group_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('photo_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('avatar_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('due_date', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DosyeGroup as SubGroups', array(
             'refClass' => 'DosyeSubGroup',
             'local' => 'dosye_group_id',
             'foreign' => 'dosye_group_id'));

        $this->hasMany('DosyePerson as Persons', array(
             'refClass' => 'DosyeGroupPerson',
             'local' => 'dosye_group_id',
             'foreign' => 'dosye_person_id'));

        $this->hasMany('DosyeFile as Files', array(
             'refClass' => 'DosyeGroupFile',
             'local' => 'dosye_group_id',
             'foreign' => 'dosye_file_id'));

        $this->hasOne('DosyeImage as AvatarImage', array(
             'local' => 'avatar_image_id',
             'foreign' => 'id'));

        $this->hasOne('DosyeImage as PhotoImage', array(
             'local' => 'photo_image_id',
             'foreign' => 'id'));

        $this->hasMany('DosyeSubGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('DosyeGroupPerson', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('DosyeGroupFile', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}