<?php

/**
 * BaseDosyeAreaLevel1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property Doctrine_Collection $DosyePerson
 * @property Doctrine_Collection $DosyeAreaLevel2
 * 
 * @method string              getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getDosyePerson()     Returns the current record's "DosyePerson" collection
 * @method Doctrine_Collection getDosyeAreaLevel2() Returns the current record's "DosyeAreaLevel2" collection
 * @method DosyeAreaLevel1     setDescription()     Sets the current record's "description" value
 * @method DosyeAreaLevel1     setDosyePerson()     Sets the current record's "DosyePerson" collection
 * @method DosyeAreaLevel1     setDosyeAreaLevel2() Sets the current record's "DosyeAreaLevel2" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyeAreaLevel1 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_area_level1');
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DosyePerson', array(
             'local' => 'id',
             'foreign' => 'address_area1'));

        $this->hasMany('DosyeAreaLevel2', array(
             'local' => 'id',
             'foreign' => 'area1_id'));
    }
}