<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $original_filename
 * @property string $internal_filename
 * @property string $description
 * @property enum $category
 * @property boolean $visible
 * @property integer $person_id
 * @property string $content_type
 * @property integer $size
 * @property string $type
 * @property integer $image_width
 * @property integer $image_height
 * @property Person $Person
 * 
 * @method string  getOriginalFilename()  Returns the current record's "original_filename" value
 * @method string  getInternalFilename()  Returns the current record's "internal_filename" value
 * @method string  getDescription()       Returns the current record's "description" value
 * @method enum    getCategory()          Returns the current record's "category" value
 * @method boolean getVisible()           Returns the current record's "visible" value
 * @method integer getPersonId()          Returns the current record's "person_id" value
 * @method string  getContentType()       Returns the current record's "content_type" value
 * @method integer getSize()              Returns the current record's "size" value
 * @method string  getType()              Returns the current record's "type" value
 * @method integer getImageWidth()        Returns the current record's "image_width" value
 * @method integer getImageHeight()       Returns the current record's "image_height" value
 * @method Person  getPerson()            Returns the current record's "Person" value
 * @method File    setOriginalFilename()  Sets the current record's "original_filename" value
 * @method File    setInternalFilename()  Sets the current record's "internal_filename" value
 * @method File    setDescription()       Sets the current record's "description" value
 * @method File    setCategory()          Sets the current record's "category" value
 * @method File    setVisible()           Sets the current record's "visible" value
 * @method File    setPersonId()          Sets the current record's "person_id" value
 * @method File    setContentType()       Sets the current record's "content_type" value
 * @method File    setSize()              Sets the current record's "size" value
 * @method File    setType()              Sets the current record's "type" value
 * @method File    setImageWidth()        Sets the current record's "image_width" value
 * @method File    setImageHeight()       Sets the current record's "image_height" value
 * @method File    setPerson()            Sets the current record's "Person" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('original_filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('internal_filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('category', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Internal',
              1 => 'Public',
              2 => 'Protected',
             ),
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content_type', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('size', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_width', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('image_height', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->setSubClasses(array(
             'Image' => 
             array(
              'type' => 'Image',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}