<?php

/**
 * BaseDosyePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $internal_id
 * @property string $first_name
 * @property string $last_name
 * @property integer $photo_image_id
 * @property integer $avatar_image_id
 * @property date $date_of_birth
 * @property string $cell_phone
 * @property string $home_phone
 * @property string $job_phone
 * @property string $other_phone
 * @property string $email
 * @property integer $nationality_id
 * @property string $identification
 * @property enum $gender
 * @property integer $marital_status_id
 * @property boolean $has_a_job
 * @property string $employment
 * @property boolean $paid_job
 * @property boolean $temporal_job
 * @property integer $address_area1
 * @property integer $address_area2
 * @property integer $address_area3
 * @property string $address_neighborhood
 * @property string $address_directions
 * @property string $church
 * @property integer $educational_level
 * @property DosyeNationality $Nationality
 * @property DosyeMaritalStatus $MaritalStatus
 * @property DosyeAreaLevel1 $AreaLevel1
 * @property DosyeAreaLevel2 $AreaLevel2
 * @property DosyeAreaLevel3 $AreaLevel3
 * @property DosyeEducationalLevel $EducationalLevel
 * @property DosyeImage $AvatarImage
 * @property DosyeImage $PhotoImage
 * @property Doctrine_Collection $Files
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $DosyeGroupPerson
 * @property Doctrine_Collection $DosyePersonFile
 * 
 * @method string                getInternalId()           Returns the current record's "internal_id" value
 * @method string                getFirstName()            Returns the current record's "first_name" value
 * @method string                getLastName()             Returns the current record's "last_name" value
 * @method integer               getPhotoImageId()         Returns the current record's "photo_image_id" value
 * @method integer               getAvatarImageId()        Returns the current record's "avatar_image_id" value
 * @method date                  getDateOfBirth()          Returns the current record's "date_of_birth" value
 * @method string                getCellPhone()            Returns the current record's "cell_phone" value
 * @method string                getHomePhone()            Returns the current record's "home_phone" value
 * @method string                getJobPhone()             Returns the current record's "job_phone" value
 * @method string                getOtherPhone()           Returns the current record's "other_phone" value
 * @method string                getEmail()                Returns the current record's "email" value
 * @method integer               getNationalityId()        Returns the current record's "nationality_id" value
 * @method string                getIdentification()       Returns the current record's "identification" value
 * @method enum                  getGender()               Returns the current record's "gender" value
 * @method integer               getMaritalStatusId()      Returns the current record's "marital_status_id" value
 * @method boolean               getHasAJob()              Returns the current record's "has_a_job" value
 * @method string                getEmployment()           Returns the current record's "employment" value
 * @method boolean               getPaidJob()              Returns the current record's "paid_job" value
 * @method boolean               getTemporalJob()          Returns the current record's "temporal_job" value
 * @method integer               getAddressArea1()         Returns the current record's "address_area1" value
 * @method integer               getAddressArea2()         Returns the current record's "address_area2" value
 * @method integer               getAddressArea3()         Returns the current record's "address_area3" value
 * @method string                getAddressNeighborhood()  Returns the current record's "address_neighborhood" value
 * @method string                getAddressDirections()    Returns the current record's "address_directions" value
 * @method string                getChurch()               Returns the current record's "church" value
 * @method integer               getEducationalLevel()     Returns the current record's "educational_level" value
 * @method DosyeNationality      getNationality()          Returns the current record's "Nationality" value
 * @method DosyeMaritalStatus    getMaritalStatus()        Returns the current record's "MaritalStatus" value
 * @method DosyeAreaLevel1       getAreaLevel1()           Returns the current record's "AreaLevel1" value
 * @method DosyeAreaLevel2       getAreaLevel2()           Returns the current record's "AreaLevel2" value
 * @method DosyeAreaLevel3       getAreaLevel3()           Returns the current record's "AreaLevel3" value
 * @method DosyeEducationalLevel getEducationalLevel()     Returns the current record's "EducationalLevel" value
 * @method DosyeImage            getAvatarImage()          Returns the current record's "AvatarImage" value
 * @method DosyeImage            getPhotoImage()           Returns the current record's "PhotoImage" value
 * @method Doctrine_Collection   getFiles()                Returns the current record's "Files" collection
 * @method Doctrine_Collection   getGroups()               Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getDosyeGroupPerson()     Returns the current record's "DosyeGroupPerson" collection
 * @method Doctrine_Collection   getDosyePersonFile()      Returns the current record's "DosyePersonFile" collection
 * @method DosyePerson           setInternalId()           Sets the current record's "internal_id" value
 * @method DosyePerson           setFirstName()            Sets the current record's "first_name" value
 * @method DosyePerson           setLastName()             Sets the current record's "last_name" value
 * @method DosyePerson           setPhotoImageId()         Sets the current record's "photo_image_id" value
 * @method DosyePerson           setAvatarImageId()        Sets the current record's "avatar_image_id" value
 * @method DosyePerson           setDateOfBirth()          Sets the current record's "date_of_birth" value
 * @method DosyePerson           setCellPhone()            Sets the current record's "cell_phone" value
 * @method DosyePerson           setHomePhone()            Sets the current record's "home_phone" value
 * @method DosyePerson           setJobPhone()             Sets the current record's "job_phone" value
 * @method DosyePerson           setOtherPhone()           Sets the current record's "other_phone" value
 * @method DosyePerson           setEmail()                Sets the current record's "email" value
 * @method DosyePerson           setNationalityId()        Sets the current record's "nationality_id" value
 * @method DosyePerson           setIdentification()       Sets the current record's "identification" value
 * @method DosyePerson           setGender()               Sets the current record's "gender" value
 * @method DosyePerson           setMaritalStatusId()      Sets the current record's "marital_status_id" value
 * @method DosyePerson           setHasAJob()              Sets the current record's "has_a_job" value
 * @method DosyePerson           setEmployment()           Sets the current record's "employment" value
 * @method DosyePerson           setPaidJob()              Sets the current record's "paid_job" value
 * @method DosyePerson           setTemporalJob()          Sets the current record's "temporal_job" value
 * @method DosyePerson           setAddressArea1()         Sets the current record's "address_area1" value
 * @method DosyePerson           setAddressArea2()         Sets the current record's "address_area2" value
 * @method DosyePerson           setAddressArea3()         Sets the current record's "address_area3" value
 * @method DosyePerson           setAddressNeighborhood()  Sets the current record's "address_neighborhood" value
 * @method DosyePerson           setAddressDirections()    Sets the current record's "address_directions" value
 * @method DosyePerson           setChurch()               Sets the current record's "church" value
 * @method DosyePerson           setEducationalLevel()     Sets the current record's "educational_level" value
 * @method DosyePerson           setNationality()          Sets the current record's "Nationality" value
 * @method DosyePerson           setMaritalStatus()        Sets the current record's "MaritalStatus" value
 * @method DosyePerson           setAreaLevel1()           Sets the current record's "AreaLevel1" value
 * @method DosyePerson           setAreaLevel2()           Sets the current record's "AreaLevel2" value
 * @method DosyePerson           setAreaLevel3()           Sets the current record's "AreaLevel3" value
 * @method DosyePerson           setEducationalLevel()     Sets the current record's "EducationalLevel" value
 * @method DosyePerson           setAvatarImage()          Sets the current record's "AvatarImage" value
 * @method DosyePerson           setPhotoImage()           Sets the current record's "PhotoImage" value
 * @method DosyePerson           setFiles()                Sets the current record's "Files" collection
 * @method DosyePerson           setGroups()               Sets the current record's "Groups" collection
 * @method DosyePerson           setDosyeGroupPerson()     Sets the current record's "DosyeGroupPerson" collection
 * @method DosyePerson           setDosyePersonFile()      Sets the current record's "DosyePersonFile" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_person');
        $this->hasColumn('internal_id', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('first_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('photo_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('avatar_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date_of_birth', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('cell_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('home_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('job_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('other_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nationality_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('identification', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('gender', 'enum', 1, array(
             'type' => 'enum',
             'length' => 1,
             'values' => 
             array(
              0 => 'M',
              1 => 'F',
             ),
             ));
        $this->hasColumn('marital_status_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('has_a_job', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('employment', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('paid_job', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('temporal_job', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('address_area1', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_area2', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_area3', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_neighborhood', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('address_directions', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('church', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('educational_level', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DosyeNationality as Nationality', array(
             'local' => 'nationality_id',
             'foreign' => 'id'));

        $this->hasOne('DosyeMaritalStatus as MaritalStatus', array(
             'local' => 'marital_status_id',
             'foreign' => 'id'));

        $this->hasOne('DosyeAreaLevel1 as AreaLevel1', array(
             'local' => 'address_area1',
             'foreign' => 'id'));

        $this->hasOne('DosyeAreaLevel2 as AreaLevel2', array(
             'local' => 'address_area2',
             'foreign' => 'id'));

        $this->hasOne('DosyeAreaLevel3 as AreaLevel3', array(
             'local' => 'address_area3',
             'foreign' => 'id'));

        $this->hasOne('DosyeEducationalLevel as EducationalLevel', array(
             'local' => 'educational_level',
             'foreign' => 'id'));

        $this->hasOne('DosyeImage as AvatarImage', array(
             'local' => 'avatar_image_id',
             'foreign' => 'id'));

        $this->hasOne('DosyeImage as PhotoImage', array(
             'local' => 'photo_image_id',
             'foreign' => 'id'));

        $this->hasMany('DosyeFile as Files', array(
             'refClass' => 'DosyePersonFile',
             'local' => 'id',
             'foreign' => 'person_id'));

        $this->hasMany('DosyeGroup as Groups', array(
             'refClass' => 'DosyeGroupPerson',
             'local' => 'id',
             'foreign' => 'person_id'));

        $this->hasMany('DosyeGroupPerson', array(
             'local' => 'id',
             'foreign' => 'person_id'));

        $this->hasMany('DosyePersonFile', array(
             'local' => 'id',
             'foreign' => 'person_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}