<?php

/**
 * BaseDosyeFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $original_filename
 * @property string $internal_filename
 * @property string $description
 * @property string $type
 * @property integer $image_width
 * @property integer $image_height
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Persons
 * @property Doctrine_Collection $Files
 * @property Doctrine_Collection $DosyePersonFile
 * @property Doctrine_Collection $DosyeGroupFile
 * 
 * @method string              getOriginalFilename()  Returns the current record's "original_filename" value
 * @method string              getInternalFilename()  Returns the current record's "internal_filename" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method string              getType()              Returns the current record's "type" value
 * @method integer             getImageWidth()        Returns the current record's "image_width" value
 * @method integer             getImageHeight()       Returns the current record's "image_height" value
 * @method Doctrine_Collection getGroups()            Returns the current record's "Groups" collection
 * @method Doctrine_Collection getPersons()           Returns the current record's "Persons" collection
 * @method Doctrine_Collection getFiles()             Returns the current record's "Files" collection
 * @method Doctrine_Collection getDosyePersonFile()   Returns the current record's "DosyePersonFile" collection
 * @method Doctrine_Collection getDosyeGroupFile()    Returns the current record's "DosyeGroupFile" collection
 * @method DosyeFile           setOriginalFilename()  Sets the current record's "original_filename" value
 * @method DosyeFile           setInternalFilename()  Sets the current record's "internal_filename" value
 * @method DosyeFile           setDescription()       Sets the current record's "description" value
 * @method DosyeFile           setType()              Sets the current record's "type" value
 * @method DosyeFile           setImageWidth()        Sets the current record's "image_width" value
 * @method DosyeFile           setImageHeight()       Sets the current record's "image_height" value
 * @method DosyeFile           setGroups()            Sets the current record's "Groups" collection
 * @method DosyeFile           setPersons()           Sets the current record's "Persons" collection
 * @method DosyeFile           setFiles()             Sets the current record's "Files" collection
 * @method DosyeFile           setDosyePersonFile()   Sets the current record's "DosyePersonFile" collection
 * @method DosyeFile           setDosyeGroupFile()    Sets the current record's "DosyeGroupFile" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyeFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_file');
        $this->hasColumn('original_filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('internal_filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_width', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('image_height', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->setSubClasses(array(
             'DosyeImage' => 
             array(
              'type' => 'Image',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DosyeGroup as Groups', array(
             'refClass' => 'DosyeGroupFile',
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('DosyePerson as Persons', array(
             'refClass' => 'DosyePersonFile',
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('DosyeGroup as Files', array(
             'refClass' => 'DosyeGroupFile',
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasMany('DosyePersonFile', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $this->hasMany('DosyeGroupFile', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}