<?php

/**
 * BasePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Nationality $Nationality
 * @property MaritalStatus $MaritalStatus
 * @property AreaLevel1 $AreaLevel1
 * @property AreaLevel2 $AreaLevel2
 * @property AreaLevel3 $AreaLevel3
 * @property EducationalLevel $EducationalLevel
 * 
 * @method Nationality      getNationality()      Returns the current record's "Nationality" value
 * @method MaritalStatus    getMaritalStatus()    Returns the current record's "MaritalStatus" value
 * @method AreaLevel1       getAreaLevel1()       Returns the current record's "AreaLevel1" value
 * @method AreaLevel2       getAreaLevel2()       Returns the current record's "AreaLevel2" value
 * @method AreaLevel3       getAreaLevel3()       Returns the current record's "AreaLevel3" value
 * @method EducationalLevel getEducationalLevel() Returns the current record's "EducationalLevel" value
 * @method Person           setNationality()      Sets the current record's "Nationality" value
 * @method Person           setMaritalStatus()    Sets the current record's "MaritalStatus" value
 * @method Person           setAreaLevel1()       Sets the current record's "AreaLevel1" value
 * @method Person           setAreaLevel2()       Sets the current record's "AreaLevel2" value
 * @method Person           setAreaLevel3()       Sets the current record's "AreaLevel3" value
 * @method Person           setEducationalLevel() Sets the current record's "EducationalLevel" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerson extends Member
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Nationality', array(
             'local' => 'nationality_id',
             'foreign' => 'id'));

        $this->hasOne('MaritalStatus', array(
             'local' => 'marital_status_id',
             'foreign' => 'id'));

        $this->hasOne('AreaLevel1', array(
             'local' => 'address_area1',
             'foreign' => 'id'));

        $this->hasOne('AreaLevel2', array(
             'local' => 'address_area2',
             'foreign' => 'id'));

        $this->hasOne('AreaLevel3', array(
             'local' => 'address_area3',
             'foreign' => 'id'));

        $this->hasOne('EducationalLevel', array(
             'local' => 'educational_level',
             'foreign' => 'id'));
    }
}