<?php

/**
 * BaseDosyePersonFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $file_id
 * @property boolean $visible
 * @property DosyePerson $Person
 * @property DosyeFile $File
 * 
 * @method integer         getPersonId()  Returns the current record's "person_id" value
 * @method integer         getFileId()    Returns the current record's "file_id" value
 * @method boolean         getVisible()   Returns the current record's "visible" value
 * @method DosyePerson     getPerson()    Returns the current record's "Person" value
 * @method DosyeFile       getFile()      Returns the current record's "File" value
 * @method DosyePersonFile setPersonId()  Sets the current record's "person_id" value
 * @method DosyePersonFile setFileId()    Sets the current record's "file_id" value
 * @method DosyePersonFile setVisible()   Sets the current record's "visible" value
 * @method DosyePersonFile setPerson()    Sets the current record's "Person" value
 * @method DosyePersonFile setFile()      Sets the current record's "File" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyePersonFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_person_file');
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DosyePerson as Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasOne('DosyeFile as File', array(
             'local' => 'file_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}