<?php

/**
 * BaseGroupingFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $grouping_id
 * @property integer $file_id
 * @property boolean $visible
 * @property Grouping $Grouping
 * @property File $File
 * 
 * @method integer      getGroupingId()  Returns the current record's "grouping_id" value
 * @method integer      getFileId()      Returns the current record's "file_id" value
 * @method boolean      getVisible()     Returns the current record's "visible" value
 * @method Grouping     getGrouping()    Returns the current record's "Grouping" value
 * @method File         getFile()        Returns the current record's "File" value
 * @method GroupingFile setGroupingId()  Sets the current record's "grouping_id" value
 * @method GroupingFile setFileId()      Sets the current record's "file_id" value
 * @method GroupingFile setVisible()     Sets the current record's "visible" value
 * @method GroupingFile setGrouping()    Sets the current record's "Grouping" value
 * @method GroupingFile setFile()        Sets the current record's "File" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupingFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grouping_file');
        $this->hasColumn('grouping_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grouping', array(
             'local' => 'grouping_id',
             'foreign' => 'id'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}