<?php

/**
 * BaseSubGrouping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $supergrouping_id
 * @property integer $subgrouping_id
 * @property Grouping $SuperGrouping
 * @property Grouping $SubGrouping
 * 
 * @method integer     getSupergroupingId()  Returns the current record's "supergrouping_id" value
 * @method integer     getSubgroupingId()    Returns the current record's "subgrouping_id" value
 * @method Grouping    getSuperGrouping()    Returns the current record's "SuperGrouping" value
 * @method Grouping    getSubGrouping()      Returns the current record's "SubGrouping" value
 * @method SubGrouping setSupergroupingId()  Sets the current record's "supergrouping_id" value
 * @method SubGrouping setSubgroupingId()    Sets the current record's "subgrouping_id" value
 * @method SubGrouping setSuperGrouping()    Sets the current record's "SuperGrouping" value
 * @method SubGrouping setSubGrouping()      Sets the current record's "SubGrouping" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubGrouping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_grouping');
        $this->hasColumn('supergrouping_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('subgrouping_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grouping as SuperGrouping', array(
             'local' => 'supergrouping_id',
             'foreign' => 'id'));

        $this->hasOne('Grouping as SubGrouping', array(
             'local' => 'subgrouping_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}