<?php

/**
 * BaseDosyeImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $DosyePerson
 * @property Doctrine_Collection $DosyeGroup
 * 
 * @method Doctrine_Collection getDosyePerson() Returns the current record's "DosyePerson" collection
 * @method Doctrine_Collection getDosyeGroup()  Returns the current record's "DosyeGroup" collection
 * @method DosyeImage          setDosyePerson() Sets the current record's "DosyePerson" collection
 * @method DosyeImage          setDosyeGroup()  Sets the current record's "DosyeGroup" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyeImage extends DosyeFile
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DosyePerson', array(
             'local' => 'id',
             'foreign' => 'avatar_image_id'));

        $this->hasMany('DosyeGroup', array(
             'local' => 'id',
             'foreign' => 'avatar_image_id'));
    }
}