<?php

/**
 * BaseDosyeEducationalLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property Doctrine_Collection $DosyePerson
 * 
 * @method string                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection   getDosyePerson() Returns the current record's "DosyePerson" collection
 * @method DosyeEducationalLevel setDescription() Sets the current record's "description" value
 * @method DosyeEducationalLevel setDosyePerson() Sets the current record's "DosyePerson" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyeEducationalLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_educational_level');
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DosyePerson', array(
             'local' => 'id',
             'foreign' => 'educational_level'));
    }
}