<?php

/**
 * BaseMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $name
 * @property integer $image_id
 * @property string $type
 * @property string $last_name
 * @property date $date_of_birth
 * @property string $cell_phone
 * @property string $home_phone
 * @property string $job_phone
 * @property string $other_phone
 * @property string $email
 * @property integer $nationality_id
 * @property string $identification
 * @property enum $gender
 * @property integer $marital_status_id
 * @property boolean $has_a_job
 * @property string $employment
 * @property boolean $paid_job
 * @property boolean $temporal_job
 * @property integer $address_area1
 * @property integer $address_area2
 * @property integer $address_area3
 * @property string $address_neighborhood
 * @property string $address_directions
 * @property string $church
 * @property integer $educational_level
 * @property string $description
 * @property date $due_date
 * @property Image $Image
 * @property Doctrine_Collection $File
 * 
 * @method string              getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method integer             getImageId()              Returns the current record's "image_id" value
 * @method string              getType()                 Returns the current record's "type" value
 * @method string              getLastName()             Returns the current record's "last_name" value
 * @method date                getDateOfBirth()          Returns the current record's "date_of_birth" value
 * @method string              getCellPhone()            Returns the current record's "cell_phone" value
 * @method string              getHomePhone()            Returns the current record's "home_phone" value
 * @method string              getJobPhone()             Returns the current record's "job_phone" value
 * @method string              getOtherPhone()           Returns the current record's "other_phone" value
 * @method string              getEmail()                Returns the current record's "email" value
 * @method integer             getNationalityId()        Returns the current record's "nationality_id" value
 * @method string              getIdentification()       Returns the current record's "identification" value
 * @method enum                getGender()               Returns the current record's "gender" value
 * @method integer             getMaritalStatusId()      Returns the current record's "marital_status_id" value
 * @method boolean             getHasAJob()              Returns the current record's "has_a_job" value
 * @method string              getEmployment()           Returns the current record's "employment" value
 * @method boolean             getPaidJob()              Returns the current record's "paid_job" value
 * @method boolean             getTemporalJob()          Returns the current record's "temporal_job" value
 * @method integer             getAddressArea1()         Returns the current record's "address_area1" value
 * @method integer             getAddressArea2()         Returns the current record's "address_area2" value
 * @method integer             getAddressArea3()         Returns the current record's "address_area3" value
 * @method string              getAddressNeighborhood()  Returns the current record's "address_neighborhood" value
 * @method string              getAddressDirections()    Returns the current record's "address_directions" value
 * @method string              getChurch()               Returns the current record's "church" value
 * @method integer             getEducationalLevel()     Returns the current record's "educational_level" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method date                getDueDate()              Returns the current record's "due_date" value
 * @method Image               getImage()                Returns the current record's "Image" value
 * @method Doctrine_Collection getFile()                 Returns the current record's "File" collection
 * @method Member              setId()                   Sets the current record's "id" value
 * @method Member              setName()                 Sets the current record's "name" value
 * @method Member              setImageId()              Sets the current record's "image_id" value
 * @method Member              setType()                 Sets the current record's "type" value
 * @method Member              setLastName()             Sets the current record's "last_name" value
 * @method Member              setDateOfBirth()          Sets the current record's "date_of_birth" value
 * @method Member              setCellPhone()            Sets the current record's "cell_phone" value
 * @method Member              setHomePhone()            Sets the current record's "home_phone" value
 * @method Member              setJobPhone()             Sets the current record's "job_phone" value
 * @method Member              setOtherPhone()           Sets the current record's "other_phone" value
 * @method Member              setEmail()                Sets the current record's "email" value
 * @method Member              setNationalityId()        Sets the current record's "nationality_id" value
 * @method Member              setIdentification()       Sets the current record's "identification" value
 * @method Member              setGender()               Sets the current record's "gender" value
 * @method Member              setMaritalStatusId()      Sets the current record's "marital_status_id" value
 * @method Member              setHasAJob()              Sets the current record's "has_a_job" value
 * @method Member              setEmployment()           Sets the current record's "employment" value
 * @method Member              setPaidJob()              Sets the current record's "paid_job" value
 * @method Member              setTemporalJob()          Sets the current record's "temporal_job" value
 * @method Member              setAddressArea1()         Sets the current record's "address_area1" value
 * @method Member              setAddressArea2()         Sets the current record's "address_area2" value
 * @method Member              setAddressArea3()         Sets the current record's "address_area3" value
 * @method Member              setAddressNeighborhood()  Sets the current record's "address_neighborhood" value
 * @method Member              setAddressDirections()    Sets the current record's "address_directions" value
 * @method Member              setChurch()               Sets the current record's "church" value
 * @method Member              setEducationalLevel()     Sets the current record's "educational_level" value
 * @method Member              setDescription()          Sets the current record's "description" value
 * @method Member              setDueDate()              Sets the current record's "due_date" value
 * @method Member              setImage()                Sets the current record's "Image" value
 * @method Member              setFile()                 Sets the current record's "File" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member');
        $this->hasColumn('id', 'string', 20, array(
             'type' => 'string',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('date_of_birth', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('cell_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('home_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('job_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('other_phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nationality_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('identification', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('gender', 'enum', 1, array(
             'type' => 'enum',
             'length' => 1,
             'values' => 
             array(
              0 => 'M',
              1 => 'F',
             ),
             ));
        $this->hasColumn('marital_status_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('has_a_job', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('employment', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('paid_job', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('temporal_job', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('address_area1', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_area2', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_area3', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_neighborhood', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('address_directions', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('church', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('educational_level', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('due_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));

        $this->setSubClasses(array(
             'Person' => 
             array(
              'type' => 'User',
             ),
             'Group' => 
             array(
              'type' => 'Group',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $this->hasMany('File', array(
             'local' => 'id',
             'foreign' => 'owned_by'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}