<?php

/**
 * BaseAreaLevel3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $area2_id
 * @property string $description
 * @property AreaLevel2 $AreaLevel2
 * @property Doctrine_Collection $Person
 * 
 * @method integer             getArea2Id()     Returns the current record's "area2_id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method AreaLevel2          getAreaLevel2()  Returns the current record's "AreaLevel2" value
 * @method Doctrine_Collection getPerson()      Returns the current record's "Person" collection
 * @method AreaLevel3          setArea2Id()     Sets the current record's "area2_id" value
 * @method AreaLevel3          setDescription() Sets the current record's "description" value
 * @method AreaLevel3          setAreaLevel2()  Sets the current record's "AreaLevel2" value
 * @method AreaLevel3          setPerson()      Sets the current record's "Person" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAreaLevel3 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area_level3');
        $this->hasColumn('area2_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AreaLevel2', array(
             'local' => 'area2_id',
             'foreign' => 'id'));

        $this->hasMany('Person', array(
             'local' => 'id',
             'foreign' => 'address_area3'));
    }
}