<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $original_filename
 * @property string $internal_filename
 * @property string $description
 * @property string $owned_by
 * @property string $type
 * @property Member $Member
 * 
 * @method string getOriginalFilename()  Returns the current record's "original_filename" value
 * @method string getInternalFilename()  Returns the current record's "internal_filename" value
 * @method string getDescription()       Returns the current record's "description" value
 * @method string getOwnedBy()           Returns the current record's "owned_by" value
 * @method string getType()              Returns the current record's "type" value
 * @method Member getMember()            Returns the current record's "Member" value
 * @method File   setOriginalFilename()  Sets the current record's "original_filename" value
 * @method File   setInternalFilename()  Sets the current record's "internal_filename" value
 * @method File   setDescription()       Sets the current record's "description" value
 * @method File   setOwnedBy()           Sets the current record's "owned_by" value
 * @method File   setType()              Sets the current record's "type" value
 * @method File   setMember()            Sets the current record's "Member" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('original_filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('internal_filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('owned_by', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'Image' => 
             array(
              'type' => 'Image',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'owned_by',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}