<?php

/**
 * BasePersonTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $team_id
 * @property Team $Team
 * @property Person $Person
 * 
 * @method integer    getPersonId()  Returns the current record's "person_id" value
 * @method integer    getTeamId()    Returns the current record's "team_id" value
 * @method Team       getTeam()      Returns the current record's "Team" value
 * @method Person     getPerson()    Returns the current record's "Person" value
 * @method PersonTeam setPersonId()  Sets the current record's "person_id" value
 * @method PersonTeam setTeamId()    Sets the current record's "team_id" value
 * @method PersonTeam setTeam()      Sets the current record's "Team" value
 * @method PersonTeam setPerson()    Sets the current record's "Person" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person_team');
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}