<?php

/**
 * BaseSubTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $superteam_id
 * @property integer $subteam_id
 * @property Team $SuperTeam
 * @property Team $SubTeam
 * 
 * @method integer getSuperteamId()  Returns the current record's "superteam_id" value
 * @method integer getSubteamId()    Returns the current record's "subteam_id" value
 * @method Team    getSuperTeam()    Returns the current record's "SuperTeam" value
 * @method Team    getSubTeam()      Returns the current record's "SubTeam" value
 * @method SubTeam setSuperteamId()  Sets the current record's "superteam_id" value
 * @method SubTeam setSubteamId()    Sets the current record's "subteam_id" value
 * @method SubTeam setSuperTeam()    Sets the current record's "SuperTeam" value
 * @method SubTeam setSubTeam()      Sets the current record's "SubTeam" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_team');
        $this->hasColumn('superteam_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('subteam_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team as SuperTeam', array(
             'local' => 'superteam_id',
             'foreign' => 'id'));

        $this->hasOne('Team as SubTeam', array(
             'local' => 'subteam_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}