<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $photo_image_id
 * @property string $description
 * @property date $due_date
 * @property Doctrine_Collection $SubTeam
 * @property Doctrine_Collection $SuperTeam
 * @property Doctrine_Collection $Person
 * @property Doctrine_Collection $File
 * @property Image $Image
 * @property Doctrine_Collection $PersonTeam
 * @property Doctrine_Collection $TeamFile
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method integer             getPhotoImageId()   Returns the current record's "photo_image_id" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method date                getDueDate()        Returns the current record's "due_date" value
 * @method Doctrine_Collection getSubTeam()        Returns the current record's "SubTeam" collection
 * @method Doctrine_Collection getSuperTeam()      Returns the current record's "SuperTeam" collection
 * @method Doctrine_Collection getPerson()         Returns the current record's "Person" collection
 * @method Doctrine_Collection getFile()           Returns the current record's "File" collection
 * @method Image               getImage()          Returns the current record's "Image" value
 * @method Doctrine_Collection getPersonTeam()     Returns the current record's "PersonTeam" collection
 * @method Doctrine_Collection getTeamFile()       Returns the current record's "TeamFile" collection
 * @method Team                setName()           Sets the current record's "name" value
 * @method Team                setPhotoImageId()   Sets the current record's "photo_image_id" value
 * @method Team                setDescription()    Sets the current record's "description" value
 * @method Team                setDueDate()        Sets the current record's "due_date" value
 * @method Team                setSubTeam()        Sets the current record's "SubTeam" collection
 * @method Team                setSuperTeam()      Sets the current record's "SuperTeam" collection
 * @method Team                setPerson()         Sets the current record's "Person" collection
 * @method Team                setFile()           Sets the current record's "File" collection
 * @method Team                setImage()          Sets the current record's "Image" value
 * @method Team                setPersonTeam()     Sets the current record's "PersonTeam" collection
 * @method Team                setTeamFile()       Sets the current record's "TeamFile" collection
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('photo_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('due_date', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Team as SubTeam', array(
             'refClass' => 'SubTeam',
             'local' => 'id',
             'foreign' => 'superteam_id'));

        $this->hasMany('Team as SuperTeam', array(
             'refClass' => 'SubTeam',
             'local' => 'id',
             'foreign' => 'subteam_id'));

        $this->hasMany('Person', array(
             'refClass' => 'PersonTeam',
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('File', array(
             'refClass' => 'TeamFile',
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasOne('Image', array(
             'local' => 'photo_image_id',
             'foreign' => 'id'));

        $this->hasMany('PersonTeam', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('TeamFile', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}