<?php

/**
 * BaseDosyeGroupPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $person_id
 * @property DosyeGroup $Group
 * @property DosyePerson $Person
 * 
 * @method integer          getGroupId()   Returns the current record's "group_id" value
 * @method integer          getPersonId()  Returns the current record's "person_id" value
 * @method DosyeGroup       getGroup()     Returns the current record's "Group" value
 * @method DosyePerson      getPerson()    Returns the current record's "Person" value
 * @method DosyeGroupPerson setGroupId()   Sets the current record's "group_id" value
 * @method DosyeGroupPerson setPersonId()  Sets the current record's "person_id" value
 * @method DosyeGroupPerson setGroup()     Sets the current record's "Group" value
 * @method DosyeGroupPerson setPerson()    Sets the current record's "Person" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDosyeGroupPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dosye_group_person');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DosyeGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('DosyePerson as Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}