<?php

/**
 * BaseTeamFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $team_id
 * @property integer $file_id
 * @property boolean $visible
 * @property Team $Team
 * @property File $File
 * 
 * @method integer  getTeamId()  Returns the current record's "team_id" value
 * @method integer  getFileId()  Returns the current record's "file_id" value
 * @method boolean  getVisible() Returns the current record's "visible" value
 * @method Team     getTeam()    Returns the current record's "Team" value
 * @method File     getFile()    Returns the current record's "File" value
 * @method TeamFile setTeamId()  Sets the current record's "team_id" value
 * @method TeamFile setFileId()  Sets the current record's "file_id" value
 * @method TeamFile setVisible() Sets the current record's "visible" value
 * @method TeamFile setTeam()    Sets the current record's "Team" value
 * @method TeamFile setFile()    Sets the current record's "File" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeamFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team_file');
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}