<?php

/**
 * BasePersonGrouping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $grouping_id
 * @property Grouping $Grouping
 * @property Person $Person
 * 
 * @method integer        getPersonId()    Returns the current record's "person_id" value
 * @method integer        getGroupingId()  Returns the current record's "grouping_id" value
 * @method Grouping       getGrouping()    Returns the current record's "Grouping" value
 * @method Person         getPerson()      Returns the current record's "Person" value
 * @method PersonGrouping setPersonId()    Sets the current record's "person_id" value
 * @method PersonGrouping setGroupingId()  Sets the current record's "grouping_id" value
 * @method PersonGrouping setGrouping()    Sets the current record's "Grouping" value
 * @method PersonGrouping setPerson()      Sets the current record's "Person" value
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonGrouping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person_grouping');
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('grouping_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grouping', array(
             'local' => 'grouping_id',
             'foreign' => 'id'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $fzblameable0 = new Doctrine_Template_fzBlameable();
        $this->actAs($timestampable0);
        $this->actAs($fzblameable0);
    }
}