all:
  stylesheets: [redmond/jquery-ui-1.8.4.custom.css]
  javascripts: [jquery-1.4.2.min.js,jquery-ui-1.8.4.custom.min.js]

searchSuccess:
  stylesheets: [-redmond/jquery-ui-1.8.4.custom.css]
  javascripts: [-jquery-1.4.2.min.js,-jquery-ui-1.8.4.custom.min.js]
