<?php

/**
 * Person
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dosye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Person extends BasePerson
{
    public function getFullName()
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function getAge()
    {
        $today = new DateTime();
        $dateOfBirth = new DateTime($this->getDateOfBirth());
        return $today->diff($dateOfBirth)->y;
    }
}
