# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        PEA - Expediente Electr贸nico
    description:  Sistema de expediente electr贸nico del Programa de Educaci贸n Abierta Vida Abundante
    keywords:     PEA, expediente, estudiantes, voluntarios, educaci贸n
    language:     es
    #robots:       index, follow

  stylesheets:    [screen.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
