<?php

/**
 * ContactMeanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactMeanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactMeanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactMean');
    }
}