File:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    original_filename: { type: string(255), notnull: true }
    internal_filename: { type: string(255), notnull: true }
    description:       { type: string(255), notnull: true }
  relations:
    Grouping:
      foreignAlias: File
      class:        Grouping
      refClass:     GroupingFile
      local:        id
      foreign:      file_id
      type:         one
    Person:
      foreignAlias: File
      class:        Person
      refClass:     PersonFile
      local:        id
      foreign:      file_id
      type:         one

Image:
  inheritance:
    extends:  File
    type:     column_aggregation
    keyField: type
    keyValue: Image
  columns:
    image_width: integer
    image_height: integer

Person:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    internal_id:          { type: string(20), notnull: true, unique: true }
    first_name:           { type: string(100), notnull: true }
    last_name:            { type: string(100), notnull: true }
    photo_image_id:       integer
    date_of_birth:        date
    cell_phone:           string(50)
    home_phone:           string(50)
    job_phone:            string(50)
    other_phone:          string(50)
    email:                string(100)
    nationality_id:       integer
    identification:       string(50)
    gender:               { type: enum, length: 1, values: ['M', 'F'] }
    marital_status_id:    integer
    has_a_job:            boolean
    employment:           string(50)
    paid_job:             boolean
    temporal_job:         boolean
    address_area1:        integer
    address_area2:        integer
    address_area3:        integer
    address_neighborhood: string(100)
    address_directions:   string(100)
    church:               string(100)
    educational_level:    integer
  relations:
    Nationality:
      class:   Nationality
      local:   nationality_id
      foreign: id
      type:    one
    MaritalStatus:
      class:   MaritalStatus
      local:   marital_status_id
      foreign: id
      type:    one
    AreaLevel1:
      class:   AreaLevel1
      local:   address_area1
      foreign: id
      type:    one
    AreaLevel2:
      class:   AreaLevel2
      local:   address_area2
      foreign: id
      type:    one
    AreaLevel3:
      class:   AreaLevel3
      local:   address_area3
      foreign: id
      type:    one
    EducationalLevel:
      class:   EducationalLevel
      local:   educational_level
      foreign: id
      type:    one
    PhotoImage:
      class:   Image
      local:   photo_image_id
      foreign: id
      type:    one
    File:
      foreignAlias: Person
      class:        File
      refClass:     PersonFile
      local:        id
      foreign:      person_id
    Grouping:
      foreignAlias: Person
      class:        Grouping
      refClass:     PersonGrouping
      local:        id
      foreign:      person_id
      type:         many

Grouping:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    name:            { type: string(100), notnull: true }
    photo_image_id:  integer
    description:     { type: string(255), notnull: true }
    due_date:        date
  relations:
    SubGrouping:
      foreignAlias: SuperGrouping
      class:        Grouping
      refClass:     SubGrouping
      local:        id
      foreign:      supergrouping_id
      type:         many
    SuperGrouping:
      foreignAlias: SubGrouping
      class:        Grouping
      refClass:     SubGrouping
      local:        id
      foreign:      subgrouping_id
      type:         many
    Person:
      foreignAlias: Grouping
      class:        Person
      refClass:     PersonGrouping
      local:        id
      foreign:      grouping_id
      type:         many
    File:
      foreignAlias: File
      class:        File
      refClass:     GroupingFile
      local:        id
      foreign:      grouping_id
      type:         many
    Image:
      class:        Image
      local:        photo_image_id
      foreign:      id
      type:         one

SubGrouping:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    supergrouping_id: { type: integer, notnull: true, primary: true }
    subgrouping_id:   { type: integer, notnull: true, primary: true }
  relations:
    SuperGrouping:
      class:        Grouping
      local:        supergrouping_id
      foreign:      id
      type:         one
    SubGrouping:
      class:        Grouping
      local:        subgrouping_id
      foreign:      id
      type:         one

PersonGrouping:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    person_id: { type: integer, notnull: true, primary: true }
    grouping_id:  { type: integer, notnull: true, primary: true }
  relations:
    Grouping:
      type: one
    Person:
      type: one

PersonFile:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    person_id: { type: integer, notnull: true, primary: true }
    file_id:   { type: integer, notnull: true, primary: true }
    visible:   { type: boolean, notnull: true, default: true }
  relations:
    Person:
      type:    one
    File:
      type:    one

GroupingFile:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    grouping_id: { type: integer, notnull: true, primary: true }
    file_id:  { type: integer, notnull: true, primary: true }
    visible:  { type: boolean, notnull: true, default: true }
  relations:
    Grouping:
      type:    one
    File:
      type:    one

Nationality:
  columns:
    description: string

MaritalStatus:
  columns:
    description: string

AreaLevel1:
  columns:
    description: string

AreaLevel2:
  columns:
    area1_id:    integer
    description: string
  relations:
    AreaLevel1:
      class:   AreaLevel1
      local:   area1_id
      foreign: id

AreaLevel3:
  columns:
    area2_id:    integer
    description: string
  relations:
    AreaLevel2:
      class:   AreaLevel2
      local:   area2_id
      foreign: id
 
EducationalLevel:
  columns:
    description: string