DosyeFile:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    original_filename: { type: string(255), notnull: true }
    internal_filename: { type: string(255), notnull: true }
    description:       { type: string(255), notnull: true }
  relations:
    Groups:
      foreignAlias: Files
      class:        DosyeGroup
      refClass:     DosyeGroupFile
      local:        id
      foreign:      file_id
    Persons:
      foreignAlias: Files
      class:        DosyePerson
      refClass:     DosyePersonFile
      local:        id
      foreign:      file_id

DosyeImage:
  inheritance:
    extends:  DosyeFile
    type:     column_aggregation
    keyField: type
    keyValue: Image
  columns:
    image_width: integer
    image_height: integer

DosyePerson:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    internal_id:          { type: string(20), notnull: true, unique: true }
    first_name:           { type: string(100), notnull: true }
    last_name:            { type: string(100), notnull: true }
    photo_image_id:       integer
    avatar_image_id:      integer
    date_of_birth:        date
    cell_phone:           string(50)
    home_phone:           string(50)
    job_phone:            string(50)
    other_phone:          string(50)
    email:                string(100)
    nationality_id:       integer
    identification:       string(50)
    gender:               { type: enum, length: 1, values: ['M', 'F'] }
    marital_status_id:    integer
    has_a_job:            boolean
    employment:           string(50)
    paid_job:             boolean
    temporal_job:         boolean
    address_area1:        integer
    address_area2:        integer
    address_area3:        integer
    address_neighborhood: string(100)
    address_directions:   string(100)
    church:               string(100)
    educational_level:    integer
  relations:
    Nationality:
      class:   DosyeNationality
      local:   nationality_id
      foreign: id
    MaritalStatus:
      class:   DosyeMaritalStatus
      local:   marital_status_id
      foreign: id
    AreaLevel1:
      class:   DosyeAreaLevel1
      local:   address_area1
      foreign: id
    AreaLevel2:
      class:   DosyeAreaLevel2
      local:   address_area2
      foreign: id
    AreaLevel3:
      class:   DosyeAreaLevel3
      local:   address_area3
      foreign: id
    EducationalLevel:
      class:   DosyeEducationalLevel
      local:   educational_level
      foreign: id
    AvatarImage:
      class:   DosyeImage
      local:   avatar_image_id
      foreign: id
    PhotoImage:
      class:   DosyeImage
      local:   photo_image_id
      foreign: id
    Files:
      foreignAlias: Persons
      class:        DosyeFile
      refClass:     DosyePersonFile
      local:        id
      foreign:      person_id
    Groups:
      foreignAlias: Persons
      class:        DosyeGroup
      refClass:     DosyeGroupPerson
      local:        id
      foreign:      person_id

DosyeGroup:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    name:            { type: string(100), notnull: true }
    photo_image_id:  integer
    avatar_image_id: integer
    description:     { type: string(255), notnull: true }
    due_date:        date
  relations:
    SubGroups:
      foreignAlias: SuperGroups
      class:        DosyeGroup
      refClass:     DosyeSubGroup
      local:        id
      foreign:      supergroup_id
    SuperGroups:
      foreignAlias: SubGroups
      class:        DosyeGroup
      refClass:     DosyeSubGroup
      local:        id
      foreign:      subgroup_id
    Persons:
      foreignAlias: Groups
      class:        DosyePerson
      refClass:     DosyeGroupPerson
      local:        id
      foreign:      group_id
    Files:
      foreignAlias: Files
      class:        DosyeFile
      refClass:     DosyeGroupFile
      local:        id
      foreign:      group_id
    AvatarImage:
      class:        DosyeImage
      local:        avatar_image_id
      foreign:      id
    PhotoImage:
      class:        DosyeImage
      local:        photo_image_id
      foreign:      id

DosyeSubGroup:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    supergroup_id: { type: integer, notnull: true, primary: true }
    subgroup_id:   { type: integer, notnull: true, primary: true }
  relations:
    SuperGroup:
      class:        DosyeGroup
      local:        supergroup_id
      foreign:      id
    SubGroup:
      class:        DosyeGroup
      local:        subgroup_id
      foreign:      id
  checks:
    notselfsubgrouping: supergroup_id <> subgroup_id


DosyeGroupPerson:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    group_id:  { type: integer, notnull: true, primary: true }
    person_id: { type: integer, notnull: true, primary: true }
  relations:
    Group:
      class:   DosyeGroup
      local:   group_id
      foreign: id
    Person:
      class:   DosyePerson
      local:   person_id
      foreign: id

DosyePersonFile:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    person_id: { type: integer, notnull: true, primary: true }
    file_id:   { type: integer, notnull: true, primary: true }
    visible:   { type: boolean, notnull: true, default: true }
  relations:
    Person:
      class:   DosyePerson
      local:   person_id
      foreign: id
    File:
      class:   DosyeFile
      local:   file_id
      foreign: id

DosyeGroupFile:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    group_id: { type: integer, notnull: true, primary: true }
    file_id:  { type: integer, notnull: true, primary: true }
    visible:  { type: boolean, notnull: true, default: true }
  relations:
    Group:
      class:   DosyeGroup
      local:   group_id
      foreign: id
    File:
      class:   DosyeFile
      local:   file_id
      foreign: id

DosyeNationality:
  columns:
    description: string

DosyeMaritalStatus:
  columns:
    description: string

DosyeAreaLevel1:
  columns:
    description: string

DosyeAreaLevel2:
  columns:
    area1_id:    integer
    description: string
  relations:
    AreaLevel1:
      class:   DosyeAreaLevel1
      local:   area1_id
      foreign: id

DosyeAreaLevel3:
  columns:
    area2_id:    integer
    description: string
  relations:
    AreaLevel2:
      class:   DosyeAreaLevel2
      local:   area2_id
      foreign: id
 
DosyeEducationalLevel:
  columns:
    description: string