File:
  actAs: { Timestampable: ~, fzBlameable: ~ }
  columns:
    original_filename: { type: string(255), notnull: true }
    internal_filename: { type: string(255), notnull: true }
    description:       { type: string(255), notnull: true }
    category:          { type: enum, values: ['Internal', 'Public', 'Protected'] }
    visible:           { type: boolean, default: true }
    person_id:         integer
    content_type:      string(50)
    size:              integer
  relations:
    Person:
      foreignAlias: Files
      class:        Person
      type:         one
      local:        person_id
      foreign:      id

Image:
  inheritance:
    extends:  File
    type:     column_aggregation
    keyField: type
    keyValue: Image
  columns:
    image_width: integer
    image_height: integer

Person:
  actAs: { Timestampable: ~, fzBlameable: ~, Commentable: ~ }
  columns:
    internal_id:          { type: string(20), notnull: true, unique: true }
    first_name:           { type: string(100), notnull: true }
    last_name:            { type: string(100), notnull: true }
    user_id:              integer
    photo_image_id:       integer
    date_of_birth:        date
    cell_phone:           string(50)
    home_phone:           string(50)
    job_phone:            string(50)
    other_phone:          string(50)
    email:                string(100)
    preferred_mean_id:    integer
    nationality_id:       integer
    identification:       string(50)
    gender:               { type: enum, length: 1, values: ['M', 'F'] }
    marital_status_id:    integer
    has_a_job:            boolean
    employment:           string(50)
    temporal_job:         boolean
    address_area1:        integer
    address_area2:        integer
    address_area3:        integer
    address_neighborhood: string(100)
    address_directions:   string(100)
    church:               string(100)
    church_begin_year:    integer
    conversion_year:      integer
    pea_begin_date:       date
    pea_finish_date:      date
    educational_level:    integer
    formation:            string(100)
  relations:
    Nationality:
      class:   Nationality
      local:   nationality_id
      foreign: id
      type:    one
    MaritalStatus:
      class:   MaritalStatus
      local:   marital_status_id
      foreign: id
      type:    one
    AreaLevel1:
      class:   AreaLevel1
      local:   address_area1
      foreign: id
      type:    one
    AreaLevel2:
      class:   AreaLevel2
      local:   address_area2
      foreign: id
      type:    one
    AreaLevel3:
      class:   AreaLevel3
      local:   address_area3
      foreign: id
      type:    one
    EducationalLevel:
      class:   EducationalLevel
      local:   educational_level
      foreign: id
      type:    one
    PhotoImage:
      class:   Image
      local:   photo_image_id
      foreign: id
      type:    one
    User:
      foreignAlias: Profile
      class:        sfGuardUser
      local:        user_id
      foreign:      id
    PreferredContactMean:
      class:   ContactMean
      local:   preferred_mean_id
      foreign: id
      type:    one

Nationality:
  columns:
    description: string

MaritalStatus:
  columns:
    description: string

AreaLevel1:
  columns:
    description: string

AreaLevel2:
  columns:
    area1_id:    integer
    description: string
  relations:
    AreaLevel1:
      class:   AreaLevel1
      local:   area1_id
      foreign: id

AreaLevel3:
  columns:
    area2_id:    integer
    description: string
  relations:
    AreaLevel2:
      class:   AreaLevel2
      local:   area2_id
      foreign: id

ContactMean:
  columns:
    description: string
    
EducationalLevel:
  columns:
    description: string
